### ISSUE TITLE
서비스 생성시 remapping 정보를 workflow에 포함하는 기능

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#34]
hic app 에서 작성한 interface 정보는 composer에서 워크플로우 저작시 블럭으로 사용할 수 있습니다. 
그리고 서비스 저작시 이 블럭에 대한 remapping 정보를 설정할 수 있습니다. 
하지만 remapping 정보가 반영되지 않기 때문에 실제 hic app 과 workflow간의 메세지 교환은 되지 않습니다. 
그렇기 때문에 서비스를 최종적으로 export 할때 hic app 에 대한 remapping 정보가 workflow에 반영될수 있도록 해야 합니다.

**Comment by eskim** [comment]
작업 완료. 확인 부탁드립니다.

**Comment by dwlee** [comment]
확인하였습니다. 
닫겠습니다.
