### ISSUE TITLE
같은 서비스 이름으로 export 할때, package.xml 에 중복되어 export 되는 경우

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#35]
만약 같은 서비스로 export 한다면, package.xml 에 두 개의 서비스가 export 되고 있습니다.
기존의 서비스가 존재하는 경우에는 하나만 되도록 수정되어야 합니다. 
추가로, 
package.xml 에 export 될때, 줄바꿈 없이 한줄에 계속 되는데 혹시 이 부분에 줄바꿈을 넣는것이 가능한가요?

**Comment by eskim** [comment]
작업 완료. 줄바꿈 부분도 수정을 하였습니다. (prettify 처리)

**Comment by dwlee** [comment]
확인하였습니다. 
이슈는 닫겠습니다.
