### ISSUE TITLE
Service 생성시 interactions 파일 작성된 내용 수정

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#36]
* name key 에는 기존의 hic app 에 등록한 name 이 들어가야 합니다. 
이 name 을 이용하여 다른 디바이스에서 interactions 을 실행합니다. 

* _id 삭제 
이 부분은 concert 에서 사용되지 않는 부분입니다.

**Comment by eskim** [comment]
수정 완료.

**Comment by dwlee** [comment]
확인하였습니다. 
이슈는 닫겠습니다.
