### ISSUE TITLE
서비스 저작시 launcher body 에 작성한 내용이 보이지 않음

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#42]
서비스 저작시 launcher body에 작성한 내용이 ui 에서 보이지 않습니다. 
하지만 브라우저의 console을 열어 확인해보면 데이터가 정상적으로 들어가 있습니다.

**Comment by eskim** [comment]
launch body 가 잘 저장이 되는것 같은데요. ui 에 표시가 되지 않는다는게 정확히 어떤 현상을 말하는지요?

혹시 이번 merge 이전에 저장했던 launch body 가 안보이는 문제인가요?

**Comment by dwlee** [comment]
네 그렇습니다. merge 이전에 작업한 부분이 ui 상에서 보이지 않습니다.

**Comment by eskim** [comment]
작업하면서 키 이름이 변경되어 그렇습니다 기존의 body 를 새로 입력해 주실수는 없나요?

**Comment by dwlee** [comment]
네 알겠습니다.

**Comment by dwlee** [comment]
해결 되었습니다. 
이슈는 닫겠습니다.
