### ISSUE TITLE
서비스 저작시 자동 저장

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#46]
현재 서비스 저작 부분이 자동저장으로 되어 있습니다. 
이 기능에 대해서 비활성화 가능한가요? 혹은 옵션으로 비활성/활성 가능한가요?

**Comment by dwlee** [comment]
모든 부분이 자동저장 되는 것이 아니라 
edit 박스로 작성되는 모든 부분이 자동으로 저장 됩니다.

**Comment by eskim** [comment]
자동저장이라는 것이 save버튼을 누르지 않아도 저장이 되어 있다는 뜻이지요? 의도한 부분이 아닙니다. 비활성화하도록 하겠습니다

**Comment by eskim** [comment]
fix 라는 commit 메세지를 쓰니 닫아져 버리네요. 확인 후 close 시켜주세요. 다시 열겠습니다.

**Comment by dwlee** [comment]
확인하였습니다. 
이슈는 닫도록 하겠습니다.
