### ISSUE TITLE
서비스 저작시 interactions에 compatibility key 추가 

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#48]
서비스 저작시 interaction 작성할때 hic app의 interaction을 저작할 경우, 자동으로 작성되기 때문에 저작자가 따로 작성해줄 필요가 없지만 
저작자가 임의로 추가하는경우 이 부분을 작성할 수 있는 방법이 없습니다. 
그래서 compatibility key를 추가하여 hic app을 사용하던, 임의로 추가하던 모두 ui에 노출되도록 해야 합니다.

**Comment by eskim** [comment]
작업완료.

**Comment by dwlee** [comment]
확인하였습니다. 이슈는 닫겠습니다.
