### ISSUE TITLE
서비스 저작시 interaction 특정 key에 대한 value의 타입정의

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#49]
현재 서비스 저작시 사용되는 모든 value는 string type으로 정의되어 있습니다. 
하지만  실제 시스템에서 int type을 요구하는 key를 요구하는 경우 문제가 발생할 수 있습니다. 
그래서 다음 key 에 관해서는 int type으로 export 될수 있도록 수정되어야 합니다. 

* interactions 의 max

**Comment by eskim** [comment]
수정 완료.

**Comment by dwlee** [comment]
확인하였습니다. 이슈는 닫겠습니다.
